# Generated by Django 5.2.7 on 2025-10-03 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0002_patient_postname"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="insurance",
        ),
        migrations.AddField(
            model_name="patient",
            name="is_subscriber",
            field=models.BooleanField(default=False),
        ),
    ]
