# Generated by Django 5.2.7 on 2025-10-15 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0003_remove_patient_insurance_patient_is_subscriber"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultation",
            name="appointment_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="consultation",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "En attente"),
                    ("IN_PROGRESS", "En cours"),
                    ("COMPLETED", "Terminée"),
                    ("CANCELLED", "Annulée"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
