# Generated by Django 5.2.7 on 2025-10-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0005_appointment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Administrateur"),
                    ("MEDICAL_ADMIN", "Médecin Administrateur"),
                    ("DOCTOR", "Médecin"),
                    ("NURSE", "Infirmier"),
                    ("SECRETARY", "Secrétaire"),
                ],
                max_length=20,
            ),
        ),
    ]
